# starts with --- for a yaml file
---

# where do you want to install or run this playbook?
- hosts: web
# would you like to see the logs?
  gather_facts: yes
# provide admin access to this playbook - use sudo
  become: true
# instructions - tasks intall nginx in agent node
  tasks:
  - name: configure/install nginx on the agent node
    apt: pkg=nginx state=present

  
# Install nodejs

# starts with --- for a yaml file
---
# where do you want to install or run this playbook?
- hosts: web

  # would you like to see the logs?
  gather_facts: yes

  # provide admin access to this playbook - use sudo
  become: true

  # instructions - tasks install nodejs in agent node
  tasks:
    - name: install nodejs and npm on the agent node
      apt: 
        pkg: 
          - nodejs
          - npm 

    - name: clone repo
      git: 
        repo: https://github.com/niamhalexandra/CI-CD_app.git
        dest: /home/ubuntu/CI-CD_app
        clone: yes
        update: yes

    - name: change directory to app
      shell: cd /home/ubuntu/CI-CD_app/app

    - name: install app dependencies
      npm:
        path: /home/ubuntu/CI-CD_app/app
        state: present



WITH THE START:


- hosts: web
  gather_facts: yes
  become: true
  tasks:
    - name: Add Node.js apt key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add Node.js 17.x apt repo
      apt_repository:
        repo: deb https://deb.nodesource.com/node_17.x bionic main
        update_cache: yes

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

   - name: Clone repo
      git:
        repo: https://github.com/niamhalexandra/CI-CD_app.git
        dest: /home/ubuntu/CI-CD_app/
        clone: yes
        update: yes
      
       - name: install dependencies
      npm:
        path: /home/ubuntu/CI-CD_app/app
        state: present

    - name: Install pm2
      npm:
        name: pm2@4.5.6  
        global: yes
        state: present
    

    - name: cd to the app directory
      shell: cd /home/ubuntu/CI-CD_app/app/

      #pm2 stop all
  - name: pm2 stop all
    command: pm2 stop all
    ignore_errors: true
    become_user: ubuntu

# Run pm2 start
  - name: Run pm2 start
    command: chdir=/home/ubuntu/repo/app/app pm2 start app.js -f
    become_user: ubuntu

   

    - name: start app
      command: pm2 start /home/ubuntu/CI-CD_app/app/app.js

